#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/STRemote/STRemote /usr/bin/STRemote

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/STRemote.service ]; then
			rm /etc/systemd/system/STRemote.service /usr/lib/systemd/system/STRemote.service /usr/lib/systemd/user/STRemote.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/STRemote/files/systemd/STRemote.service /usr/lib/systemd/system/STRemote.service
		# try fix error in Ubuntu 18.04
		# Failed to reload STRemote.service: Unit STRemote.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/STRemote.service:10: Executable path is not absolute: pkill -f "STRemote --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/STRemote.service
		fi
		systemctl daemon-reload
		systemctl enable STRemote
		systemctl start STRemote
	fi
fi
