name: Build STRemote

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          
      - name: Build
        run: cargo build --release
        
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: StaffTrackerRemote
          path: target/release/*.exe
